pipeline{
    
  agent{
       docker{
         image 'maven:3.6.1-jdk-8-slim'
         args '-v $HOME/.m2:/root/.m2'
       }

   }
	
    stages{
        stage('build'){
            steps{
                echo 'this is build step'
				dir('worker'){
                  sh 'mvn compile'
				}
            } 
        }
        stage('test'){
            steps{
                echo 'this is test stage'
                dir('worker'){
                  sh 'mvn clean test'
				}
            } 
        }
        stage('package'){
            steps{
                echo 'this is package stage'
                dir('worker'){
                  sh 'mvn package -DskipTests'
				  archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
				}
            } 
        }
    }
    
    post{
        always{
            echo 'This job is complete'
            
        }
        failure{
            echo 'failure'
            
        }
    }
}
